# Generated by Django 5.1.2 on 2024-11-02 08:22

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_channel_banner_remove_channel_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path),
        ),
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_icon_upload_path, validators=[server.validators.validate_icon_image_size]),
        ),
    ]
